### ISSUE TITLE
Should this be a standards track specification?

### ISSUE THREAD

**Issue by cabo** [cbor-wg/cddl-control#10]
See comment number 2 in Tianran Zhou's opsdir review <https://mailarchive.ietf.org/arch/msg/last-call/37Q3zW3Sj9gDOBUF_wODcQ-WgAI>

**Comment by chrysn** [comment]
As explained in more detail in that thread, please resolve by switching to standards track.

**Comment by cabo** [comment]
Closed by e82ef96
